name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: "Test on Node"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v10-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: "https://registry.npmjs.org"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v10-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: |
          ORG_NAME=$(echo ${{ github.ref }} | sed -r "s/refs\/tags\/(.+?)-.+@.+/\1/")
          API_NAME=$(echo ${{ github.ref }} | sed -r "s/refs\/tags\/.+?-(.+?)@.+/\1/")
          npm run update $ORG_NAME $API_NAME
          npm run build apis/$ORG_NAME/$API_NAME
          cd apis/$ORG_NAME/$API_NAME
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
